### ISSUE TITLE
[Cancelled] BuRN

### ISSUE THREAD

**Issue by RileyTuoti** [opportunity-hack/2020-summer-volunteer-internship#2]
## BuRN

- Riley Tuoti @RileyTuoti 
- Noah Carlow @NoahCarlow 
- Ben Hay @Qworks

- Focus: Notification System
- #2020-team-burn

**Comment by gregv** [comment]
Monday/Wednesday standups created
![image](https://user-images.githubusercontent.com/6913307/81828376-97e95500-94ee-11ea-8b88-57f0a1dc6937.png)

**Comment by gregv** [comment]
The team has decided to cancel this project - closing this ticket
